server:
  # gzip压缩
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: text/plain,text/xml,application/xml,application/json
  port: 9001
  undertow:
    accesslog:
      enabled: true
      pattern: '[%{time,yyyy-MM-dd HH:mm:ss.S z}] %m %U "%q" %s (%D ms) %b %{i,X-B3-TraceId},%{i,X-B3-SpanId} %{i,X-Real-IP} %{i,Referer} "%{i,User-Agent}" %{i,Platform} %l %u %I %v %a'
      prefix: utils_access_log.
      suffix: log
      dir: logs/runtime/
      rotate: true

spring:
  profiles:
    active: local
    #多个配置文件以逗号分隔
    include: loveit


  application:
    name: utils
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  freemarker:
    # 是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
    allow-request-override: false
    # 是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性。
    allow-session-override: false
    # 是否启用模板缓存。
    cache: false
    # 模板编码。
    charset: "UTF-8"
    # 是否检查模板位置是否存在。
    check-template-location: true
    # Content-Type value.
    content-type: "text/html"
    # 是否启用freemarker
    enabled: true
    # 设定所有request的属性在merge到模板的时候，是否要都添加到model中.
    expose-request-attributes: false
    # 是否在merge模板的时候，将HttpSession属性都添加到model中
    expose-session-attributes: false
    # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    expose-spring-macro-helpers: true
    # 是否优先从文件系统加载template，以支持热加载，默认为true
    prefer-file-system-access: true
    # 设定模板的后缀.
    suffix: ".ftl"
    # 设定模板的加载路径，多个以逗号分隔，默认:
    template-loader-path: "classpath:/templates/"
    settings:
      # 设定FreeMarker keys.
      template_update_delay: 0
      default_encoding: "UTF-8"
      classic_compatible: true
debug: false
