#基本目录

base: "/Users/hejiadong/src/java/maosong"

#项目目录
project:
  root:
    directory: "${base}/datingpaas"
    #备份目录
    backupDirectory: "${base}/datingpaas/backup"
    service: "${base}/datingpaas/datingpaas-service"


# dto
dto:
  root:
    directory: "${project.root.service}/src/main/java/com/datingpaas/model/dto"

#converter
converter:
  root:
    directory: "${project.root.service}/src/main/java/com/datingpaas/model/converter/mapstruct"

#vo
vo:
  root:
    directory: "${project.root.service}/src/main/java/com/datingpaas/model/vo"

#dao
dao:
  root:
    directory: "${project.root.service}/src/main/java/com/datingpaas/dao"

#service
service:
  root:
    directory: "${project.root.service}/src/main/java/com/datingpaas/service"

#bff工程名
bff:
  root: "${base}/datingpaas/datingpaas-gfun-bff"

#业务控制器
controller:
  root:
    directory: "${bff.root}/src/main/java/com/datingpaas/api"

  dto:
    directory: "${bff.root}/src/main/java/com/datingpaas/dto"

  vo:
    directory: "${bff.root}/src/main/java/com/datingpaas/vo"

  converter:
    directory: "${bff.root}/src/main/java/com/datingpaas/converter"


# 验单
strategy:
  root:
    directory: "${project.root.service}/src/main/java/com/datingpaas/common/strategy/impl"
