#基本目录

base: "/Users/hejiadong/src/java/maosong"

#项目目录
project:
  root:
    directory: "${base}/datingpaas"
    #备份目录
    backupDirectory: "${base}/datingpaas/backup"


# dto
dto:
  root:
    directory: "${base}/datingpaas/datingpaas-service/src/main/java/com/datingpaas/model/dto"

#converter
converter:
  root:
    directory: "${base}/datingpaas/datingpaas-service/src/main/java/com/datingpaas/model/converter/mapstruct"

#vo
vo:
  root:
    directory: "${base}/datingpaas/datingpaas-service/src/main/java/com/datingpaas/model/vo"

#dao
dao:
  root:
    directory: "${base}/datingpaas/datingpaas-service/src/main/java/com/datingpaas/dao"

#service
service:
  root:
    directory: "${base}/datingpaas/datingpaas-service/src/main/java/com/datingpaas/service"

#业务控制器
controller:
  root:
    directory: "${base}/datingpaas/datingpaas-gfun-bff/src/main/java/com/datingpaas/api"
  dto:
    directory: "${base}/datingpaas/datingpaas-gfun-bff/src/main/java/com/datingpaas/dto"
  vo:
    directory: "${base}/datingpaas/datingpaas-gfun-bff/src/main/java/com/datingpaas/vo"
  converter:
    directory: "${base}/datingpaas/datingpaas-gfun-bff/src/main/java/com/datingpaas/converter"