#基本目录

base: "/Users/hejiadong/src/java/maosong"

#项目目录
project:
  root:
    # 项目根目录
    directory: "${base}/loveit"
    #备份目录
    backupDirectory: "${project.root.directory}/backup"
    # 中间层，service
    service: "${project.root.directory}/data-service"

# dto
dto:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/dto"

#converter
converter:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/converter"

#vo
vo:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/vo"

#dao
dao:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/dao"

#service
service:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/services"

#bff工程名
bff:
  # /Users/hejiadong/src/java/maosong/lovit/app_server
  root: "${project.root.directory}/app_server"

#业务控制器
controller:
  root:
    # /Users/hejiadong/src/java/maosong/lovit/app_server/src/main/java/com/mason/lovit/api
    directory: "${bff.root}/src/main/java/com/mason/lovit/api"

  dto:
    directory: "${bff.root}/src/main/java/com/mason/lovit/dto"

  vo:
    directory: "${bff.root}/src/main/java/com/mason/lovit/vo"

  converter:
    directory: "${bff.root}/src/main/java/com/mason/lovit/converter"


# 验单 strategy.root.directory
strategy:
  root:
    directory: "${project.root.service}/src/main/java/com/datingpaas/common/strategy/impl"
