#基本目录

base: "/Users/hejiadong/src/java/maosong"

#项目目录
project:
  root:
    # 项目根目录
    directory: "${base}/loveit"
    #备份目录
    backupDirectory: "${project.root.directory}/backup"
    # 中间层，service
    service: "${project.root.directory}/data-service"

# dto
dto:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/dto"
    package_name: "com.mason.dto"

#converter
converter:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/converter"
    package_name: "com.mason.converter"

#vo
vo:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/vo"
    package_name: "com.mason.vo"

#dao
dao:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/dao"
    package_name: "com.mason.dao"

#service
service:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/services"
    package_name: "com.mason.services"

#entity
entity:
  root:
    directory: "${project.root.service}/src/main/java/com/mason/dao/entity"
    package_name: "com.mason.dao.entity"

#bff工程名
bff:
  root: "${project.root.directory}/app_server"

#业务控制器
controller:
  root:
    directory: "${bff.root}/src/main/java/com/mason/lovit/api"
    package_name: "com.mason.lovit.api"
  version: " "

  dto:
    directory: "${bff.root}/src/main/java/com/mason/lovit/dto"
    package_name: "com.mason.lovit.dto"

  vo:
    directory: "${bff.root}/src/main/java/com/mason/lovit/vo"
    package_name: "com.mason.lovit.vo"

  converter:
    directory: "${bff.root}/src/main/java/com/mason/lovit/converter"
    package_name: "com.mason.lovit.converter"


# 验单
strategy:
  root:
    directory: ""
    package_name: ""